name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: code
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: code

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        working-directory: ./code
        run: ./gradlew test
  
  instrumented-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4 # Similar to above, check out your code to run

      - name: Enable KVM  
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      
      - name: Setup node
        uses: actions/setup-node@v4
      
      - name: Install and Run Firebase
        run: npm install -g firebase-tools
      
      - name: Start Emulator
        run: firebase emulators:start --only firestore &
        working-directory: code

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
          working-directory: code
